WeAreFarmGeek/diplomat

spec/configure_spec.rb

Tests were failing because the random order caused one test to side effect of another.

Add a configuration initializer to enable random testing.

---

lib/diplomat/service.rb
spec/configure_spec.rb
spec/service_spec.rb

Here is a start for adding the ability to send in options and get back meta data about requests.
This is for the service get function.  If y'all are good with this pattern, I'll look into adding the others. 
I don't know the others just yet for my project, but I will.

Add options and meta data return for service get calls

---

lib/diplomat/configuration.rb
lib/diplomat/kv.rb
spec/configure_spec.rb
spec/kv_spec.rb

Added new configuration parameter acl_token.
Set: Diplomat.configuration.acl_token = token
Reworked the #get, #put, #delete methods to be more flexible, for adding more parameters in the future.
Added context for tests, to differentiate them easier.

Added support for acl_token in K/V store

---

README.md
lib/diplomat/lock.rb
lib/diplomat/session.rb

Various fixed to the Session and Lock code:
- README.md says Session.create can take a hash, and indeed it can, but it's rendered to a URL-encoded body by the current code. Change to render to JSON.
- Session create request bodies should only specify certain keys (which override defaults). README.md listed arbitrary keys, possibly confusing the Session and Lock objects? Fixed to use valid keys.
- Session create request bodies are optional; each value has a sane default.
- Acquiring a lock is actually the act of writing a value to a key, so the value should be able to be specified (the consul docs recommend using this value to record something about the lock holder).

Session and Lock fixes

---

lib/diplomat/kv.rb

I know Ruby 1.8 is old, but I still have to use it, and currently all of the code in lib/ works on 1.8, with the exception of these two lines, recently added in a5056ea. I'd like to keep on top of the 1.8 compatibility while it's still easy. There really isn't a great loss here, it's only hash syntax, not a massive increase in verbosity or a loss in functionality.
I've left the tests alone - they contain quite a lot of newer ruby syntax, and have done for a while.

Use ruby 1.8 syntax in production code.

---

lib/diplomat/service.rb
spec/service_spec.rb

Howdy,
I'm working on integrating diplomat in our org, and one thing that I can see as being super helpful in the near-to-mid term is the ability to query on a service per datacenter. I've added the support based on the [query string documented in the consul docs](https://consul.io/docs/agent/http/catalog.html#catalog_service).
It's just piggy-backing on the basic pattern you already have in place for adding query strings from the options hash. Specs covering the additionally query string are also implemented. I didn't add any specs covering the cases where there are 2 of 3 options present, but I'm happy to do so if you'd like.

Add a dc option to the service interface

---

lib/diplomat/service.rb
spec/service_spec.rb

It would be nice to have this feature.
Not sure about the implementation though, let me know if I should change anything.

adds #register and #deregister to Service

---

lib/diplomat/event.rb
lib/diplomat/kv.rb

This is very similar to PR#22, which I notice was never finished and is now out of date, as it's based on the code prior to me adding all the extra arguments and code to Kv#get.
This patch maintains the default behavior of Kv|Event#get, but allows the user to request a "null" value rather than an exception, using the existing not_found parameter. It also makes that parameter more similar to the found parameter, simplifying the API.
The default value can't be specified, I think that's a step too far, but I think the values are sensible. I've got the for identity element of the type String and Array - "" and [], rather than nil. This is because they're nulipotent in most operations like + and <<, whereas nil is often used to signal an error and propagates. If the user considers the missing …

Add option to return default value rather than throw when keys, events aren't found

---

README.md
lib/diplomat/configuration.rb
lib/diplomat/rest_client.rb
spec/configure_spec.rb

With additional configuration options you can now use client certs like this:
``` ruby
require "openssl"
Diplomat.configure do |config|
config.url = "https://server.dc1.consul:8501"
config.options = {ssl: {
client_cert: OpenSSL::X509::Certificate.new(File.read("client.crt")),
client_key: OpenSSL::PKey::RSA.new(File.read("client.key")),
ca_file: "ca.crt",
verify: true
}}
end
```
Faraday's options are described [here](https://github.com/lostisland/faraday/blob/c2f325a3298a8c71d0f0b3b93f24d0f0f7409302/lib/faraday.rb#L44), its Net::HTTP specific SSL options are described [here](https://github.com/lostisland/faraday/blob/c2f325a3298a8c71d0f0b3b93f24d0f0f7409302/lib/faraday/adapter/net_http.rb#L98).

Add optional configuration options for Faraday

---

README.md
lib/diplomat.rb
lib/diplomat/datacenter.rb
spec/datacenter_spec.rb

Example Usage:
```
Diplomat::Datacenter.get.each { |dc|
Diplomat::Service.get('redis', :all, { :dc => dc }).each { |service|
puts "   server %s %s:$s  check inter 1000 weight 100 " % [service.Node, service.Address, service.ServicePort]
}
}
```

Added datacenter option to get a list of avaliable datacenters

---

lib/diplomat/rest_client.rb
spec/kv_spec.rb

If we create a blank folder on the consul ui, and add keys later, and try to fetch it using ```?recurse```, the returned array contains a key ```folder_name/``` whose value is nil.
Checking for nil inside map doesn't work here as the hash is still returned with value ```nil```. Only base64 decoding is avoided for nil values.

Reject nil values.

---

lib/diplomat/session.rb

`Diplomat::Session.list` failed as follows:
```ruby
session_id = Diplomat::Session.create({Name: 'foo'})
Diplomat::Session.list
=> Faraday::ResourceNotFound: the server responded with status 404
```
accoding to api document, endpoing of Lists all active sessions is
`/v1/session/list`, not `/v1/session/list/`.
see : https://www.consul.io/docs/agent/http/session.html#session_list

trim trailing slash of path

---

README.md
lib/diplomat/service.rb
lib/diplomat/version.rb
spec/service_spec.rb

Adding a method to list all the services.
This might be useful in case you want to know what services are registered without having to query consul for all of them.

Get all services

---

lib/diplomat/kv.rb
lib/diplomat/rest_client.rb
spec/kv_spec.rb

An option to return kv keys (mainly dirs) with null values  is critical in some cases.

option to return keys/dirs with null values

---

lib/diplomat.rb
lib/diplomat/acl.rb
lib/diplomat/api_options.rb
lib/diplomat/error.rb
lib/diplomat/kv.rb
lib/diplomat/version.rb
spec/acl_spec.rb

This patch adds support for consul acl. It allows to create/update/destroy/list and get info on acls.
It also factorize the common options used.

Add support for acls

---

README.md
lib/diplomat/service.rb
spec/service_spec.rb

Add support for querying all services by datacenter
The existing `Service#get_all` method doesn't allow specifying a datacenter when querying, and will only return services for the default datacenter of the agent serving the API. This is especially useful when accessing a WAN consul cluster via another cluster, e.g. when the former is inaccessible due to firewall rules.
Included are specs, the function change and documentation changes (rdoc and README).
Thanks for taking a look, please let me know if this needs any work.

Service class: get_all services by datacenter

---

lib/diplomat/node.rb
lib/diplomat/nodes.rb
spec/nodes_spec.rb

i noticed that i could curl and get all nodes, but not with your api. this uses the same convention you have for getting all services.
https://www.consul.io/docs/agent/http/catalog.html#catalog_nodes

allow for a datacenter when getting all nodes

---

diplomat.gemspec

@johnhamelink I noticed that you restricted the json version in 5c92c0bbffad7b1096644ea9eab5dc9bd2349d89. Could that restriction be lifted? The reason I ask is because this restriction conflicts with a lot of other gems.
```
spec.add_runtime_dependency "json", "~> 1.8"
```
https://github.com/WeAreFarmGeek/diplomat/blob/4152f810014fcbc02e92fe566ad6fa32d95495e4/diplomat.gemspec#L22

Remove restriction on json version

---

lib/diplomat/lock.rb
spec/lock_spec.rb

The ACL specs were also incorrect so I cleaned those up while I added tests around the cases when an ACL token is or is not configured.

Add the ACL token, if configured, to `lock` calls

---

lib/diplomat/acl.rb
spec/acl_spec.rb

According to https://www.consul.io/docs/agent/http/acl.html, when the
acl does not exist, return value is "null" instead of nothing.
Fixes #71

Improve acl info method when the acl does not exist

---

README.md
lib/diplomat/node.rb
lib/diplomat/version.rb
spec/node_spec.rb

Adds missing `Diplomat::Nodes#register` and `Diplomat::Nodes#deregister` methods.
* [`/v1/catalog/register` Endpoint](https://www.consul.io/docs/agent/http/catalog.html#catalog_register)
* [`/v1/catalog/deregister` Endpoint](https://www.consul.io/docs/agent/http/catalog.html#catalog_deregister)

Adding ability to register/deregister nodes

---

README.md
lib/diplomat.rb
lib/diplomat/maintenance.rb
spec/maintenance_spec.rb

Adds wrappers around the `/v1/agent/maintenance` endpoint and a helper method `#enabled` to determine if a host is already in maintenance mode.

Add Diplomat::Maintenance class with #enable and #enabled?

---

README.md
lib/diplomat/node.rb
spec/node_spec.rb

`/v1/catalog/nodes` allows a `dc` param, this PR adds support for that via options.

Add dc param support to Diplomat::Node.get_all

---

lib/diplomat/service.rb

e.g. when you get connection refused it is confusing, as you just get
Diplomat::PathNotFound: Diplomat::PathNotFound
with this change you get
Diplomat::PathNotFound: Failed to open TCP connection to 192.168.174.132:8501 (Connection refused - connect(2) for "192.168.174.132" port 8501)

include error message in exception

---

lib/diplomat/rest_client.rb
spec/rest_client_spec.rb

While I was testing a tool which uses Diplomat, I noticed that I was not able to mock the 'accessible methods'.
For this to work, `#respond_to_missing?` is needed to return `true` for methods 'created' with `#method_missing`. Added it (and `#respond_to?`) to `Diplomat::RestClient` as class methods.

Add .respond_to? and .respond_to_missing? to Diplomat::RestClient

---

CHANGELOG.md
lib/diplomat/health.rb
spec/health_spec.rb

This allows for using `options[:tag]` with `Health.service`.

Allow for tag option with Health.service

---

lib/diplomat/kv.rb
spec/kv_spec.rb

The return from `parse_body` wasn't being saved so furthur calls to use
the _parsed_body_ would fail.
Fixes #104

Fixes recursive blocking Kv queries

---

CHANGELOG.md
lib/diplomat/acl.rb
lib/diplomat/kv.rb
lib/diplomat/maintenance.rb
lib/diplomat/rest_client.rb
spec/maintenance_spec.rb

Threading Consul errors through to `Diplomat::UnknownStatus` messages would help a lot when triaging application exceptions.

Include Consul errors in Diplomat::UnknownStatus messages

---

lib/diplomat/lock.rb

Hi !
Thanks for this great gem , and your great work
I just noticed that `raw.body.inspect = "true\n"`
This makes `raw.body == 'true'` test always false.
So currently `lock.acquire` def always return false and it makes `wait_to_acquire` looping endlessly :)
This simple modification (adding a `.strip`) should make this test works as intended.
Thanks !

Fix lock.acquire return status

---

CHANGELOG.md
lib/diplomat/acl.rb
lib/diplomat/kv.rb
lib/diplomat/lock.rb
spec/acl_spec.rb
spec/kv_spec.rb
spec/lock_spec.rb

As of Consul 0.7.2 pretty-printing is enabled by default in dev mode. This causes incorrect interpretation of return values for a couple of endpoints. This PR changes the equality checks to use ~~`start_with?`~~ the `chomp`'d response instead.
Let me know if you have any suggestions. Thanks for the nice lib!

Defend against newlines added by Consul in dev mode

---

CHANGELOG.md
lib/diplomat/event.rb

Consul events can be targeted to another datacenter by specifying `?dc=foo` this adds an argument to the fire method to allow another dc to be specified

allow specifying the datacenter for an event

---

lib/diplomat/kv.rb
spec/kv_spec.rb

In my testing of transaction support, an aborted transaction does
not necessarily contain a Results field, causing decode_transaction
to crash. Fix and add a test.

Fix parsing of aborted transactions with missing Results field

---

lib/diplomat/kv.rb
lib/diplomat/rest_client.rb
lib/diplomat/service.rb
spec/kv_spec.rb

fix single key/value in Diplomat::Kv.get with conver_to_hash options ON

fix single key/value in Diplomat::Kv.get with convert_to_hash option ON

---

.idea/vcs.xml
lib/diplomat/rest_client.rb

Related to https://github.com/lostisland/faraday/pull/685 and fixes #148

Do not set the adapter on faraday prior the request

---

lib/diplomat/kv.rb

* Allow Diplomat::KV.put to acquire a session of asked for key
* Allow Diplomat::KV.put to acquire a session of asked for key
Consul allows for a simple leader election facility by applying session keys to k/v objects. This allows you to acquire session keys when creating k/v and getting them during query.
https://www.consul.io/docs/guides/leader-election.html

    * Allow Diplomat::KV.get to return Session of asked for key

---

diplomat.gemspec

Fixes #144. The `json` library is bundled with Ruby starting with version 1.9.3. As such, there's no need to specify the `json` gem as a dependency on these Ruby versions.

Don't install the `json` gem unnecessarily

---

CHANGELOG.md
diplomat.gemspec
lib/diplomat/configuration.rb
lib/diplomat/kv.rb
lib/diplomat/rest_client.rb
lib/diplomat/service.rb
spec/agent_spec.rb
spec/service_spec.rb

Consul 1.0 has started to enforce the verbs used:
*https://www.consul.io/docs/upgrade-specific.html#http-verbs-are-enforced-in-many-http-apis

Use `PUT` as the verb for deregistering a service.

---

README.md

This PR is just a suggested README change, but it fixes two issues concerning ACL tokens. The [Consul documentation](https://www.consul.io/api/index.html#authentication) says:
> When authentication is enabled, a Consul token should be provided to API requests using the X-Consul-Token header. This reduces the probability of the token accidentally getting logged or exposed. [...] Previously this was provided via a ?token= query parameter. This functionality exists on many endpoints for backwards compatibility, but its use is highly discouraged, since it can show up in access logs as part of the URL.
The `config.acl_token` setting in Diplomat sets the `token` query string parameter rather than the header. Additionally, it does not set it for all API endpoints (e.g., Sessions), so some …

Suggest using X-Consul-Token for ACL tokens

---

.travis.yml

This PR only updates the CI matrix to the latest generally available Ruby versions.
Source for version numbers: https://github.com/rvm/rvm/blob/master/config/known
I included 2.6.0-rc1, since its release is so near, and it would be nice to support it as soon as possible. **Update**: 2.6.0-rc2.

CI: Update to current set of Rubies

---

lib/diplomat/check.rb

Support for passing Output field in consul TTL checks as described here: https://www.consul.io/api/agent/check.html

Support for Output in TTL checks

---

diplomat.gemspec
lib/diplomat/rest_client.rb
spec/kv_spec.rb

if real_size is zero, ie
:key => 'foo'
:value => 'bar'
convert_to_hash creates 'foo '=> {} rather than 'foo' => 'bar'

simpler convert_to_hash function

---

lib/diplomat/lock.rb
spec/lock_spec.rb

It is useful to be able to set the flags attribute on the KVPair created for lock acquisition. This PR modifies the acquire, wait_for_acquire, and release methods for Diplomat::Lock so that a value can be passed in and adds additional unit tests to cover the added code.

Set flags attribute on KVPair during lock acquisition and release

---

README.md

Most common options are:
* dc: target datacenter
* token: identity used to perform the corresponding action
* http_addr: to target a remote consul node
* stale: use consistency mode that allows any server to service the read regardless of whether it is the leader
Also fix some markdown syntax

Add some options example in the documentation

---

lib/diplomat/rest_client.rb

This syntax error breaks the whole release.

fix syntax error  '=>'  instead of colon

---

Gemfile
bin/consul-cli.rb
diplomatic_bag.gemspec
lib/diplomat/rest_client.rb
lib/diplomatic_bag.rb
lib/diplomatic_bag/datacenters.rb
lib/diplomatic_bag/info.rb
lib/diplomatic_bag/nodes.rb
lib/diplomatic_bag/service.rb
lib/diplomatic_bag/services.rb

Diplomatic_Bag is a library that uses Diplomat to provide useful method.
consul-cli.rb is a usage of these method usable in command line.
```
USAGE: consul-cli.rb [[action]] [[options]]
consul-cli.rb services list [options]
consul-cli.rb service status <service-name> [options]
consul-cli.rb info [options]
consul-cli.rb nodes list-duplicate-id [options]
Options:
-a, --http-addr		The `address` and port of the Consul HTTP agent
-d, --datacenter	Name of the datacenter to query
-f, --format		Output format (json|text)
-t, --token		ACL token to use in the request
```

Add simple tool to provide useful commands

---

lib/diplomat/service.rb
spec/service_spec.rb

Hello there!
I noticed that it was not possible to request a service while passing multiple tags.
Consider for example a service like this:
```sh
consul services register -id="service-sometag-someothertag" -name "service" (...)  -tag sometag -tag someothertag
```
Consul allows you to retrieve it like this:
```sh
curl "http://localhost:8500/v1/catalog/service/service?tag=sometag&tag=someothertag"
```
This was however not supported by Diplomat, so I extended the `:tag` option to also allow an array of tags. The semantics are the same as in consul, all passed tags must match.

Allow providing multiple tags when get'ing a service

---

lib/diplomat/rest_client.rb
lib/diplomat/service.rb

I hate to be that guy, but the previous patch I submitted did not work due to an incompatibility in how Faraday works with URLs and how Consul does that.
As far as I can find, consul expects the tags variable to repeated to provide multiple tags:
```
http://localhost:8500/v1/catalog/service/my-service?tag=sometag&tag=someothertag
```
Whereas faraday (by default) expects repeated occurrences to have `[]` in their key name:
```
http://localhost:8500/v1/catalog/service/my-service?tag[]=sometag&tag[]=someothertag
```
Furthermore, if you do it the way that faraday doesn't expect but consul does, only the _last_ occurance of the key is kept, so the url actually becomes this:
```
http://localhost:8500/v1/catalog/service/my-service?tag=someothertag
```
Luckily, faraday allows overriding this …

Allow overriding the params_encoder when making requests to consul

---

lib/diplomat.rb
lib/diplomat/error.rb
lib/diplomat/role.rb
lib/diplomat/token.rb
spec/policy_spec.rb
spec/role_spec.rb
spec/token_spec.rb

Consul 1.5.0 introduced a number of changes (https://github.com/hashicorp/consul/blob/master/CHANGELOG.md#150-may-08-2019):
- ability to specify `AccessorID` and `SecretID` (need valid UUIDs though)
- ability to bind policies to roles (`Diplomat::Role` is added here)
This PR fixes the issue #195.
I'll open an issue for `ACL Auth Method HTTP API` and `ACL Binding Rule HTTP API` support but it won't be covered in this PR as I don't have access to a k8s cluster right now.
**Please do not merge this PR until `WIP` is removed from subject as testing is in progress.**
Thanks for reviewing it @pierresouchay 🇫🇷

add Diplomat::Role for Consul ACL roles in 1.5.x

---

CHANGELOG.md
lib/diplomat/kv.rb
lib/diplomat/lock.rb
lib/diplomat/rest_client.rb

The same was done for GET in 58fff34c6072d21519512dbaefb4d0c46aa11ac9
but wasn't applied across the board.

Trim leading slashes from keys in more places

---

README.md
lib/diplomat/kv.rb
spec/kv_spec.rb

Adds `get_all` method to KV class to provide consistent behavior and return types when recursively retrieving keys. The specific issue raised in #162 is that `get('foo', recurse: true)` returns just the value if there is only one key returned. `get_all('foo')` will always return an Array regardless of number of results. The `convert_to_hash` option is also supported.
As the new method shares a lot of the same logic as `get`, I moved certain functionality into new common methods invoked by both `get` and `get_all` to avoid duplicating the same code in two spots.
Fixes #162

adds get_all method

---

diplomat.gemspec
lib/diplomat/rest_client.rb

I ran in to a gem conflict with the latest release of Chef Infra Client since they are now using faraday 1.0.0 in their bundled ruby. Reading the [upgrade guide for faraday](https://github.com/lostisland/faraday/blob/master/UPGRADING.md#errors), it seems like this may be the only fix needed to get the current version of diplomat working with faraday 1.0.0
This change passes `rake` using both faraday 1.0.0 and 0.17.3

support faraday 1.0.0

---

lib/diplomat/rest_client.rb
spec/kv_spec.rb

As of https://github.com/WeAreFarmGeek/diplomat/pull/176, `require 'diplomat'` also calls `require 'deep_merge'`, which monkey-patches `Hash#deep_merge`. This is unnecessary – Diplomat could `require 'deep_merge/core` and call `DeepMerge.deep_merge!` directly. This is important for codebases that are sensitive to core monkey-patches.
Thank you

Avoid `Hash#deep_merge` monkeypatch

---

CHANGELOG.md
lib/diplomat/health.rb
lib/diplomat/rest_client.rb
lib/diplomat/service.rb
spec/health_spec.rb
spec/kv_spec.rb

This is doing a couple things to bring this gem more in alignment with the expectations of the Consul API:
1. It is generalizing the Faraday connection to always use `FlatParamsEncoder`. This is because Consul's API has already taken the stance that they do not expect multiple params to be specified using `[]` but instead by simply repeating the same query param multiple times.
2. Adding support to `Diplomat::Health.service` for specifying an array of tags when querying for a service's health checks
Fixes #212

Add multiple tag suppport

---

.github/workflows/ruby.yml
.rubocop.yml
CHANGELOG.md
diplomat.gemspec
diplomatic_bag.gemspec
lib/diplomat/version.rb
spec/spec_helper.rb

Bump all gem dependencies

---

CHANGELOG.md
lib/diplomat/health.rb
spec/health_spec.rb

This ports similar blocking read support over from `Diplomat::Service.get` so that a similar pattern can be utilized when retrieving service health information.
Fixes #221

Add blocking query support for service health
