- README.md
- lib/diplomat.rb
- lib/diplomat/error.rb
- lib/diplomat/event.rb
- lib/diplomat/kv.rb
- lib/diplomat/rest_client.rb
- spec/event_spec.rb
A module for events (including an abstraction over consul's API - which returns a list of all events - to get particular ones in the sequence, e.g. the more recent). Plus some tidying up.
> [WIP] Events

- README.md
This functionality is already in kv.rb but it wasn't documented
> Add example of ACL tokens into Readme.md

- lib/diplomat/kv.rb
- lib/diplomat/version.rb
This let's us do something like 
``foo = Diplomat::Kv.get('/test', {:recurse => true})``
Which will return all values under /test
> Add recursion option so we can grab keys recursively

- README.md
- lib/diplomat/session.rb
- spec/session_spec.rb
I added the functions and tests for session renewal and the 'list' function for sessions.  If you'd like something additional, let me know.
> Add session renewal, session listing

- lib/diplomat/session.rb
> Fixing bug in Session.renew

- lib/diplomat/kv.rb
- lib/diplomat/rest_client.rb
- lib/diplomat/version.rb
- spec/kv_spec.rb
Added the keys and separator params on K/V GET
> Add keys and separator options

- .travis.yml
- lib/diplomat/health.rb
- spec/health_spec.rb
Because I don't see any activity from @sammarx and I need this feature I've added test for #70 PR.
@PeterFCaswell does it looks good to you?
> Health options dc

- lib/diplomat/kv.rb
Option for getting ModifyIndex value to put into `:cas`
> Add options to get ModifyIndex value

- lib/diplomat/kv.rb
- lib/diplomat/rest_client.rb
- spec/kv_spec.rb
This option will allow to get consul response with decoded value.
It is useful to get at the same time the value and the modify_index
> Add decode_values option for Kv.get

- lib/diplomat/kv.rb
- lib/diplomat/rest_client.rb
- spec/kv_spec.rb
This is instead of #57
Allows to pass callable object which can be used to transform values before they are returned by Kv.get
> kv value transformations

- lib/diplomat/service.rb
- spec/service_spec.rb
> Add external service registration

- lib/diplomat/event.rb
- lib/diplomat/node.rb
- lib/diplomat/service.rb
- spec/event_spec.rb
- spec/node_spec.rb
- spec/service_spec.rb
Hi,
ACL token is missing in Node, Service and Event classes. Sorry for little bit of chaos around this pull and pull #81.
> Support ACL for Node, Service and Event classes

- CHANGELOG.md
- CONTRIBUTING.md
Add a (partial) changelog and a contributing guide which can be referred to when submitting PRs.
> Changelog and contributing guide

- README.md
Useful for debugging and backup.
> Note on listing all keys

- CHANGELOG.md
- lib/diplomat/kv.rb
- spec/kv_spec.rb
Fixes WeAreFarmGeek/diplomat#99
Hey guys! This adds recursive delete support.  Let me know what I can do to get this merged. Thanks!
> Add support for recursive delete

- CHANGELOG.md
- README.md
- lib/diplomat/kv.rb
- lib/diplomat/rest_client.rb
- lib/helpers/to_hash.rb
- spec/kv_spec.rb
This functionality converts the (potentially) nested data in consul to a nested ruby hash.
> Converting data to a ruby hash

- Rakefile
- diplomat.gemspec
* Add Rubocop support and rake task
* Update version of rake
* Add author
> Update rakefile and gemspec

- CHANGELOG.md
- README.md
- lib/diplomat.rb
- lib/diplomat/status.rb
- spec/status_spec.rb
https://github.com/WeAreFarmGeek/diplomat/issues/98
> Adding cluster status API endpoint

- CHANGELOG.md
- lib/diplomat/kv.rb
- lib/diplomat/rest_client.rb
- lib/diplomat/version.rb
- spec/kv_spec.rb
This reverts commit e4b8878f242699dd683d5dc1db56ed2bce365968 (#120).
> Revert "Resolve inconsistent recursive return for Diplomat::KV.get"

- .rubocop.yml
- .travis.yml
- diplomat.gemspec
- lib/diplomat.rb
- lib/diplomat/kv.rb
- lib/diplomat/rest_client.rb
- lib/diplomat/service.rb
- spec/agent_spec.rb
Will allow to register services with tokens
> Support for tokens when registering/unregistering entities on Agent

- lib/diplomat/kv.rb
This might fix: https://github.com/WeAreFarmGeek/diplomat/issues/171
> Avoid having a HTTP 302 if key requested starts with '/'

- lib/diplomat/acl.rb
- lib/diplomat/check.rb
- lib/diplomat/kv.rb
- lib/diplomat/node.rb
- lib/diplomat/query.rb
- lib/diplomat/rest_client.rb
- lib/diplomat/service.rb
- spec/lock_spec.rb
- spec/service_spec.rb
As every data was converted to json, raw data usage was impossible
Reverting all json conversion to source function and remove systematic conversion.
Fixes: #187
> Fix raw data usage in kv

- lib/diplomat.rb
- lib/diplomat/error.rb
- lib/diplomat/policy.rb
- lib/diplomat/rest_client.rb
- lib/diplomat/token.rb
- spec/policy_spec.rb
- spec/token_spec.rb
Related to #193, adding two new classes, Policy and Token.
~This is a work in progress.~
I vaguely remember having rights on the repository 🤷‍♂
> [WIP] Support Consul 1.4.x ACLs 

- CHANGELOG.md
- README.md
- lib/diplomat.rb
- lib/diplomat/autopilot.rb
- spec/autopilot_spec.rb
Addresses #206 
This is the initial support for the Autopilot endpoint which will:
* Get the current configuration being used by Autopilot
* Get the status from Autopilot
> Autopilot Support

- CHANGELOG.md
- lib/diplomat/health.rb
- lib/diplomat/rest_client.rb
- spec/health_spec.rb
add ability to set cached param for health requests
> Add cached param service node

- README.md
- lib/diplomat/health.rb
The informations provided by the endpoints are different enough to make it worthwhile.
> Allow use of filters on every Health methods
